### ISSUE TITLE
Assess CWL to WDL converter.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#114]
http://gatkforums.broadinstitute.org/wdl/discussion/8454/feedback-on-initial-version-of-bcbio-wdl-converted-from-cwl

**Comment by jasonwalker80** [comment]
Using a miniconda2 environment, I installed cwl2wdl like so:
`pip install -e git+https://github.com/chapmanb/cwl2wdl.git#egg=cwl2wdl`

**Comment by jasonwalker80** [comment]
First attempt:

```
jwalker@linus2112:/gscmnt/gc2764/cad/jwalker/toil_test/arvados_trial/detect_variants 510>cwl2wdl detect_variants.cwl
Traceback (most recent call last):
  File "/gscuser/jwalker/git/miniconda2/bin/cwl2wdl", line 9, in <module>
    load_entry_point('cwl2wdl', 'console_scripts', 'cwl2wdl')()
  File "/gscuser/jwalker/src/cwl2wdl/cwl2wdl/main.py", line 58, in cli
    CwlParser(arguments.FILE).parse_document()
  File "/gscuser/jwalker/src/cwl2wdl/cwl2wdl/parsers.py", line 37, in parse_document
    workflow = self.__parse_cwl_workflow(cwl, sourceDir, parentFileName)
  File "/gscuser/jwalker/src/cwl2wdl/cwl2wdl/parsers.py", line 114, in __parse_cwl_workflow
    inputs = self.__parse_cwl_inputs(cwl_workflow['inputs'])
  File "/gscuser/jwalker/src/cwl2wdl/cwl2wdl/parsers.py", line 189, in __parse_cwl_inputs
    cwl_input['id'].strip("#")
```

**Comment by jasonwalker80** [comment]
Given my limited python experience, I probably need help with this one.

**Comment by jasonwalker80** [comment]
Although the converters exist, they are not full-featured. Some manual conversion is still required.
