### ISSUE TITLE
Error while running rnaseq workflow

### ISSUE THREAD

**Issue by FarahZKhan** [genome/analysis-workflows#292]
Hello, 
I am trying to execute the [rnaseq workflow](https://github.com/genome/cancer-genomics-workflow/blob/toil_compatibility/rnaseq/workflow.cwl) using [example data](https://github.com/genome/cancer-genomics-workflow/tree/toil_compatibility/example_data/rnaseq). 
It returns this error for the first step while running [bam_to_fastq.cwl](https://github.com/genome/cancer-genomics-workflow/blob/toil_compatibility/rnaseq/bam_to_fastq.cwl)

```
00:15:49.314 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/farahkhan/Documents/cancer-genomics-workflow/rnaseq/picard.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Tue Jun 12 00:15:49 AEST 2018] SamToFastq INPUT=/private/var/folders/tl/1j6jy66x3nvfbxt8ycs_q21m0000gn/T/tmpUE9q8H/stgc8eb7bb3-0f75-4cda-9d5b-40faaffad4a2/gerald_H3MYFBBXX_4_GCCAAT_1k.bam FASTQ=/private/tmp/docker_tmpA2umUG/read1.fastq SECOND_END_FASTQ=/private/tmp/docker_tmpA2umUG/read2.fastq    OUTPUT_PER_RG=false COMPRESS_OUTPUTS_PER_RG=false RG_TAG=PU RE_REVERSE=true INTERLEAVE=false INCLUDE_NON_PF_READS=false CLIPPING_MIN_LENGTH=0 READ1_TRIM=0 READ2_TRIM=0 INCLUDE_NON_PRIMARY_ALIGNMENTS=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Jun 12 00:15:49 AEST 2018] Executing as farahkhan@Farahs-MacBook-Pro.local on Mac OS X 10.10.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 10.0.1+10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.7-SNAPSHOT
[Tue Jun 12 00:15:49 AEST 2018] picard.sam.SamToFastq done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=134217728
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 1, Read name K00193:38:H3MYFBBXX:4:1101:10003:10036, RG ID on SAMRecord not found in header: 2895626107
	at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:454)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:812)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.<init>(BAMFileReader.java:783)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.<init>(BAMFileReader.java:771)
	at htsjdk.samtools.BAMFileReader.getIterator(BAMFileReader.java:474)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.iterator(SamReader.java:478)
	at picard.sam.SamToFastq.doWork(SamToFastq.java:191)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
[job bam_to_fastq] completed permanentFail
[step bam_to_fastq] completed permanentFail
```
I think the example file does not have a header. 
Can you please advise on how to tackle this issue?

**Comment by chrisamiller** [comment]
We seemed to have missed this issue way back when.  The pipeline has been extensively updated over the past 18 months.  If you're still having problems, please open a new issue.  Thanks!
