### ISSUE TITLE
${VARIABLE} should be escaped

### ISSUE THREAD

**Issue by serge2016** [genome/analysis-workflows#838]
Hello!
Such an error already was corrected by escaping `${VAR}` like `\${VAR}`. It is only about variables in brackets `{`...:
https://github.com/genome/analysis-workflows/blob/295e7b7f51727c0f2d6cc86ce817449b2e8dba3c/definitions/tools/cnvnator.cwl#L37

**Comment by tatahin** [comment]
Error:
```
(function(){SAMPLE})()
stdout was: ''
stderr was: 'evalmachine.<anonymous>:142
(function(){SAMPLE})()
            ^

ReferenceError: SAMPLE is not defined
    at evalmachine.<anonymous>:142:13
    at evalmachine.<anonymous>:142:21
    at Script.runInContext (vm.js:137:20)
    at Script.runInNewContext (vm.js:143:17)
    at Object.runInNewContext (vm.js:309:38)
    at Socket.<anonymous> ([eval]:11:57)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:282:13)
    at Socket.Readable.push (_stream_readable.js:220:10)'
```
