### ISSUE TITLE
vcf_sanitize.cwl fails - output missing expected field. 

### ISSUE THREAD

**Issue by tirohia** [genome/analysis-workflows#895]
I'm trying to run vcf_santize.cwl as part of a germline variant detection process. As best I can tell, subworkflows/varscan_germline.cwl is calling  fp_filter.cwl, which is calling vcf_sanitize.cwl

The javascript in the output definition of vcf_sanitize.cwl, is initially unable to execute.  It requires the inclusion of InlineJavascriptRequirement class in the requirements section. Additionally the javascript currently reads:
```
            glob: |
                  ${
                    if(inputs.vcf.nameext.equals(".gz")){
                      return inputs.vcf.nameroot.replace(/.vcf$/, "") + ".sanitized.vcf.gz";
                    }
                    return inputs.vcf.nameroot + ".sanitized.vcf.gz";
                  }
```
 The line 
```
                    if(inputs.vcf.nameext.equals(".gz")){
```
needs to be changed to 
```
                    if(inputs.vcf.nameext === (".gz")){
```
Where the string comparison is made in other cwl files, i.e. tools/manta_somatic.cwl, it is made in this style, rather than .equals()

After adding in the InlineJavascriptRequirement in the requirements section, but without the above substituion of === for .equals(), the following error occurs:

```

ERROR [job sanitize_vcf] Job error:
('Error collecting output for parameter \'sanitized_vcf\':
    tools/vcf_sanitize.cwl:46:13: Expression evaluation error:
    tools/vcf_sanitize.cwl:46:13: Expecting value: line 1 column 1 (char 0)
    tools/vcf_sanitize.cwl:46:13: script was:
    t$ols/vcf_sanitize.cwl:46:13: 01 "use strict";
    tools/vcf_sanitize.cwl:46:13: 02 var inputs = {
    tools/vcf_sanitize.cwl:46:13: 03     "vcf": {
    tools/vcf_sanitize.cwl:46:13: 04         "location": "file:///blue/project/gridssTest/data/tmp/rsxlaffj/output.vcf.gz",
    tools/vcf_sanitize.cwl:46:13: 05         "basename": "output.vcf.gz",
    tools/vcf_sanitize.cwl:46:13: 06         "nameroot": "output.vcf",
    tools/vcf_sanitize.cwl:46:13: 07         "nameext": ".gz",
    tools/vcf_sanitize.cwl:46:13: 08         "class": "File", 
    tools/vcf_sanitize.cwl:46:13: 09         "checksum": "sha1$356b1e0f4f194c278b981851e392ac8647fb84ac",
    tools/vcf_sanitize.cwl:46:13: 10         "size": 660,
    tools/vcf_sanitize.cwl:46:13: 11         "secondaryFiles": [
    tools/vcf_sanitize.cwl:46:13: 12          {
    tools/vcf_sanitize.cwl:46:13: 13          "basename": "output.vcf.gz.tbi",
    tools/vcf_sanitize.cwl:46:13: 14          "location": "file:///blue/project/gridssTest/data/tmp/rsxlaffj/output.vcf.gz.tbi",
    tools/vcf_sanitize.cwl:46:13: 15          "class": "File",
    tools/vcf_sanitize.cwl:46:13: 16          "nameroot": "output.vcf.gz",
    tools/vcf_sanitize.cwl:46:13: 17          "nameext": ".tbi",
    tools/vcf_sanitize.cwl:46:13: 18          "checksum": "sha1$27a0f22e02be99c928cf13e818eb7523636c5929",
    tools/vcf_sanitize.cwl:46:13: 19          "size": 72, 
    tools/vcf_sanitize.cwl:46:13: 20          "http://commonwl.org/cwltool#generation": 0,
    tools/vcf_sanitize.cwl:46:13: 21          "path": "/var/lib/cwl/stgbe39f376-3889-4ad1-b932-c229af8574f0/output.vcf.gz.tbi",
    tools/vcf_sanitize.cwl:46:13: 22          "dirname": "/var/lib/cwl/stgbe39f376-3889-4ad1-b932-c229af8574f0"
    tools/vcf_sanitize.cwl:46:13: 23             }
    tools/vcf_sanitize.cwl:46:13: 24         ],
    tools/vcf_sanitize.cwl:46:13: 25         "http://commonwl.org/cwltool#generation": 0,
    tools/vcf_sanitize.cwl:46:13: 26         "path": "/var/lib/cwl/stgbe39f376-3889-4ad1-b932-c229af8574f0/output.vcf.gz",
    tools/vcf_sanitize.cwl:46:13: 27         "dirname": "/var/lib/cwl/stgbe39f376-3889-4ad1-b932-c229af8574f0"
    tools/vcf_sanitize.cwl:46:13: 28     }
    tools/vcf_sanitize.cwl:46:13: 29 };
    tools/vcf_sanitize.cwl:46:13: 30 var self = null;
    tools/vcf_sanitize.cwl:46:13: 31 var runtime = {
    tools/vcf_sanitize.cwl:46:13: 32     "cores": 1,
    tools/vcf_sanitize.cwl:46:13: 33     "ram": 4000,
    tools/vcf_sanitize.cwl:46:13: 34     "tmpdirSize": 1024,
    tools/vcf_sanitize.cwl:46:13: 35     "outdirSize": 1024,
    tools/vcf_sanitize.cwl:46:13: 36     "tmpdir": "/tmp",
    tools/vcf_sanitize.cwl:46:13: 37     "outdir": "/akmLPP"
    tools/vcf_sanitize.cwl:46:13: 38 };
    tools/vcf_sanitize.cwl:46:13: 39 (function(){
    tools/vcf_sanitize.cwl:46:13: 40   if(inputs.vcf.nameext.equals(".gz")){
    tools/vcf_sanitize.cwl:46:13: 41     return $nputs.vcf.nameroot.replace(/.vcf$/, "") + ".sanitized.vcf.gz";
    tools/vcf_sanitize.cwl:46:13: 42   }
    tools/vcf_sanitize.cwl:46:13: 43   return inputs.vcf.nameroot + ".sanitized.vcf.gz";
    tools/vcf_sanitize.cwl:46:13: 44 })()
    tools/vcf_$anitize.cwl:46:13: stdout was: \'\'
    tools/vcf_sanitize.cwl:46:13: stderr was: \'evalmachine.<anonymous>:40
    tools/vcf_sanitize.cwl:46:13:   if(inputs.vcf.nameext.equals(".gz")){
    tools/vcf_sanitize.cwl:46:13:         ^
    $ools/vcf_sanitize.cwl:46:13: 
    tools/vcf_sanitize.cwl:46:13: TypeError: inputs.vcf.nameext.equals is not a function
    tools/vcf_sanitize.cwl:46:13:     at evalmachine.<anonymous>:40:25
    tools/vcf_sanitize.cwl:46:13:     at evalmachine.<an$nymous>:44:3 
    tools/vcf_sanitize.cwl:46:13:     at ContextifyScript.Script.runInContext (vm.js:59:29)
    tools/vcf_sanitize.cwl:46:13:     at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    tools/vcf_sanitize.cwl:46:13:     at Objec$.runInNewContext (vm.js:135:38)
    tools/vcf_sanitize.cwl:46:13:     at Socket.<anonymous> ([eval]:11:57)
    tools/vcf_sanitize.cwl:46:13:     at emitOne (events.js:116:13)
    tools/vcf_sanitize.cwl:46:13:     at Socket.emit (events.js:211:7)
    tools/vcf_sanitize.cwl:46:13:     at addChunk (_stream_readable.js:263:12)
    tools/vcf_sanitize.cwl:46:13:     at readableAddChunk (_stream_readable.js:246:13)\'', {})
WARNING [job sanitize_vcf] completed permanentFail
```

**Comment by tmooney** [comment]
Thanks for the detailed report!  I've opened #896 to address these issues.
